version: '3.9'
services:
  web:
    container_name: todos
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
        - "5005:5000"
    depends_on:
        - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ConcerninglyUnsecurePassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql